# Generated by Django 4.0.6 on 2022-08-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
